export type Subject={id:string;name:string}
export type Topic={id:string;subjectId:string;name:string}
export type QuestionSession={id:string;date:string;subjectId:string;topicId:string;quantity:number;correct:number;observation:string}
export type ErrorStatus='Pendente'|'Revisado'|'Dominado'
export type ErrorReason='Não conhecia o conteúdo'|'Confundi conceitos'|'Errei por interpretação'|'Errei por distração'|'Errei cálculo'|'Chutei'|'Esqueci o conteúdo'
export type Review={id:string;date:string;note:string}
export type ErrorEntry={id:string;date:string;subjectId:string;topicId:string;question:string;reason:ErrorReason;whatWentWrong:string;correctConcept:string;nextReview:string;lastReview:string;status:ErrorStatus;reviews:Review[]}
export type ScheduleStatus='Planejado'|'Em andamento'|'Concluído'|'Não realizado'
export type ScheduleEntry={id:string;date:string;start:string;end:string;subjectId:string;topicId:string;planned:number;actual:number;status:ScheduleStatus;note:string}
export type Settings={userName:string;weeklyHoursGoal:number;weeklyQuestionsGoal:number;masteryPercentage:number}
export type StudyState={subjects:Subject[];topics:Topic[];sessions:QuestionSession[];errors:ErrorEntry[];schedule:ScheduleEntry[];settings:Settings;theme:'light'|'dark';addSubject:(name:string)=>void;updateSubject:(id:string,name:string)=>void;deleteSubject:(id:string)=>void;addTopic:(subjectId:string,name:string)=>void;updateTopic:(id:string,name:string)=>void;deleteTopic:(id:string)=>void;addSession:(session:Omit<QuestionSession,'id'>)=>void;updateSession:(id:string,session:Omit<QuestionSession,'id'>)=>void;deleteSession:(id:string)=>void;addError:(error:Omit<ErrorEntry,'id'>)=>void;updateError:(id:string,error:Partial<ErrorEntry>)=>void;deleteError:(id:string)=>void;addSchedule:(entry:Omit<ScheduleEntry,'id'>)=>void;updateSchedule:(id:string,entry:Partial<ScheduleEntry>)=>void;deleteSchedule:(id:string)=>void;updateSettings:(settings:Partial<Settings>)=>void;setTheme:(theme:'light'|'dark')=>void;resetDemo:()=>void;clearAll:()=>void}
const subjects:Subject[]=['Português','Direito Constitucional','Direito Administrativo','Raciocínio Lógico','Informática'].map((name,i)=>({id:`s${i+1}`,name}))
const topicNames=[['Interpretação de texto','Classes gramaticais','Concordância verbal'],['Direitos fundamentais','Organização do Estado','Controle de constitucionalidade'],['Atos administrativos','Licitações','Serviços públicos'],['Proposições lógicas','Porcentagem e razão','Análise combinatória'],['Segurança da informação','Pacote Office','Redes de computadores']]
const topics:Topic[]=topicNames.flatMap((names,i)=>names.map((name,j)=>({id:`t${i}${j}`,subjectId:`s${i+1}`,name})))
const days=(n:number)=>new Date(Date.now()-n*86400000).toISOString().slice(0,10),future=(n:number)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10)
const reasons:ErrorReason[]=['Não conhecia o conteúdo','Confundi conceitos','Errei por interpretação','Errei por distração','Errei cálculo','Chutei','Esqueci o conteúdo']
const errors:ErrorEntry[]=Array.from({length:14},(_,i)=>({id:`e${i+1}`,date:days(i+2),subjectId:`s${i%5+1}`,topicId:`t${i%5}0`,question:`Questão sobre ${topicNames[i%5][0]} — item ${i+1}`,reason:reasons[i%reasons.length],whatWentWrong:'Identifiquei a alternativa errada, mas ainda preciso reforçar o raciocínio usado.',correctConcept:'Revisar a regra principal e aplicar o conceito em novas questões.',nextReview:i<2?days(i+1):future(i-4),lastReview:i%3===0?days(3):days(i+2),status:i<5?'Pendente':i<10?'Revisado':'Dominado',reviews:[{id:`r${i}a`,date:days(i+2),note:'Erro registrado na sessão de questões.'}]}))
const schedule:ScheduleEntry[]=[{id:'sc1',date:new Date().toISOString().slice(0,10),start:'07:30',end:'08:30',subjectId:'s1',topicId:'t00',planned:60,actual:52,status:'Concluído',note:'Revisão matinal'},{id:'sc2',date:new Date().toISOString().slice(0,10),start:'19:00',end:'20:00',subjectId:'s3',topicId:'t20',planned:60,actual:0,status:'Planejado',note:'Bloco de teoria'},{id:'sc3',date:new Date(Date.now()+86400000).toISOString().slice(0,10),start:'18:00',end:'19:30',subjectId:'s4',topicId:'t30',planned:90,actual:0,status:'Planejado',note:'Exercícios'},{id:'sc4',date:new Date(Date.now()-86400000).toISOString().slice(0,10),start:'20:00',end:'21:00',subjectId:'s2',topicId:'t10',planned:60,actual:38,status:'Não realizado',note:'Retomar conteúdo'}]
export const demoData={subjects,topics,schedule,sessions:[0,1,2,3,4,5,6].map((d,i)=>({id:`q${i}`,date:days(d),subjectId:`s${i%5+1}`,topicId:`t${i%5}0`,quantity:20+i*3,correct:14+i*2,observation:i%2?'Revisão do bloco':'Sessão de estudo'})),errors,settings:{userName:'João',weeklyHoursGoal:20,weeklyQuestionsGoal:150,masteryPercentage:80}}
export const pct=(correct:number,total:number)=>total?Math.round(correct/total*100):0
export const topicPerformance=(topicId:string,sessions:QuestionSession[])=>{const rows=sessions.filter(s=>s.topicId===topicId);const q=rows.reduce((a,s)=>a+s.quantity,0);const c=rows.reduce((a,s)=>a+s.correct,0);return {q,c,e:q-c,percentage:pct(c,q)}}
export const subjectPerformance=(subjectId:string,sessions:QuestionSession[])=>{const rows=sessions.filter(s=>s.subjectId===subjectId);const q=rows.reduce((a,s)=>a+s.quantity,0);const c=rows.reduce((a,s)=>a+s.correct,0);return {q,c,e:q-c,percentage:pct(c,q)}}
export type {StudyState}
