export type TopicStatus = 'Não iniciado' | 'Estudando' | 'Revisando' | 'Dominado'
export type Subject = { id: string; name: string }
export type Topic = { id: string; subjectId: string; name: string; status: TopicStatus }
export type QuestionSession = { id: string; date: string; subjectId: string; topicId: string; quantity: number; correct: number; observation: string }
export type Settings = { userName: string; weeklyHoursGoal: number; weeklyQuestionsGoal: number; masteryPercentage: number }
export type StudyState = { subjects: Subject[]; topics: Topic[]; sessions: QuestionSession[]; settings: Settings; theme: 'light' | 'dark'; addSubject: (name: string) => void; updateSubject: (id: string, name: string) => void; deleteSubject: (id: string) => void; addTopic: (subjectId: string, name: string) => void; updateTopic: (id: string, name: string, status: TopicStatus) => void; deleteTopic: (id: string) => void; addSession: (session: Omit<QuestionSession, 'id'>) => void; updateSession: (id: string, session: Omit<QuestionSession, 'id'>) => void; deleteSession: (id: string) => void; updateSettings: (settings: Partial<Settings>) => void; setTheme: (theme: 'light' | 'dark') => void; resetDemo: () => void; clearAll: () => void }

const subjects: Subject[] = ['Português','Direito Constitucional','Direito Administrativo','Raciocínio Lógico','Informática'].map((name, i) => ({ id: `s${i+1}`, name }))
const topicNames = [['Interpretação de texto','Classes gramaticais','Concordância verbal'],['Direitos fundamentais','Organização do Estado','Controle de constitucionalidade'],['Atos administrativos','Licitações','Serviços públicos'],['Proposições lógicas',' porcentagem e razão','Análise combinatória'],['Segurança da informação','Pacote Office','Redes de computadores']]
const topics: Topic[] = topicNames.flatMap((names, i) => names.map((name, j) => ({ id: `t${i}${j}`, subjectId: `s${i+1}`, name: name.trim(), status: (j === 0 ? 'Estudando' : j === 1 ? 'Revisando' : 'Não iniciado') as TopicStatus })))
const sessions: QuestionSession[] = [0,1,2,3,4,5,6].map((d, i) => ({ id: `q${i}`, date: new Date(Date.now()-d*86400000).toISOString().slice(0,10), subjectId: `s${i%5+1}`, topicId: `t${i%5}0`, quantity: 20+i*3, correct: 14+i*2, observation: i%2 ? 'Revisão do bloco' : 'Sessão de estudo' }))
export const demoData = { subjects, topics, sessions, settings: { userName: 'João', weeklyHoursGoal: 20, weeklyQuestionsGoal: 150, masteryPercentage: 80 } }

import { create } from 'zustand'
import { persist } from 'zustand/middleware'
export const useStudyStore = create<StudyState>()(persist((set) => ({ ...demoData, theme: 'light', addSubject: (name) => set(s => ({ subjects: [...s.subjects, { id: crypto.randomUUID(), name }] })), updateSubject: (id,name) => set(s => ({ subjects: s.subjects.map(x => x.id===id ? {...x,name}:x) })), deleteSubject: (id) => set(s => ({ subjects:s.subjects.filter(x=>x.id!==id), topics:s.topics.filter(x=>x.subjectId!==id), sessions:s.sessions.filter(x=>x.subjectId!==id) })), addTopic: (subjectId,name) => set(s => ({ topics:[...s.topics,{id:crypto.randomUUID(),subjectId,name,status:'Não iniciado'}] })), updateTopic: (id,name,status) => set(s => ({ topics:s.topics.map(x=>x.id===id?{...x,name,status}:x) })), deleteTopic: (id) => set(s => ({ topics:s.topics.filter(x=>x.id!==id), sessions:s.sessions.filter(x=>x.topicId!==id) })), addSession: (session) => set(s => ({sessions:[...s.sessions,{...session,id:crypto.randomUUID()}]})), updateSession: (id,session) => set(s => ({sessions:s.sessions.map(x=>x.id===id?{...session,id}:x)})), deleteSession: (id) => set(s => ({sessions:s.sessions.filter(x=>x.id!==id)})), updateSettings: (settings) => set(s => ({settings:{...s.settings,...settings}})), setTheme: (theme) => set({theme}), resetDemo: () => set({...demoData}), clearAll: () => set({subjects:[],topics:[],sessions:[]}), }), { name:'aprova-track-store' }))
