'use client'
import { useState } from 'react'
import { Modal } from '@/components/layout/modal'
import { pct,subjectPerformance,topicPerformance } from '@/types/study'
import type {ErrorEntry,ErrorReason,ErrorStatus,StudyState} from '@/types/study'
import { BookOpen,CircleHelp,ChevronRight,Filter,Plus,Pencil,Trash2,NotebookPen,TriangleAlert } from 'lucide-react'
import { Metric } from '@/components/dashboard/cards'

export function ErrorModal({store,item,close}:{store:StudyState;item:Partial<ErrorEntry>|undefined;close:()=>void}){const [subjectId,setSubjectId]=useState(item?.subjectId||store.subjects[0]?.id||''),[topicId,setTopicId]=useState(item?.topicId||''),[date,setDate]=useState(item?.date||new Date().toISOString().slice(0,10)),[question,setQuestion]=useState(item?.question||''),[reason,setReason]=useState<ErrorReason>(item?.reason||'Não conhecia o conteúdo'),[wrong,setWrong]=useState(item?.whatWentWrong||''),[concept,setConcept]=useState(item?.correctConcept||''),[next,setNext]=useState(item?.nextReview||new Date(Date.now()+86400000).toISOString().slice(0,10)),[status,setStatus]=useState<ErrorStatus>(item?.status||'Pendente');const topics=store.topics.filter(t=>t.subjectId===subjectId);return <Modal title="Adicionar erro" close={close}><form className="form-grid error-form" onSubmit={e=>{e.preventDefault();if(!question.trim()||!topicId)return;store.addError({date,subjectId,topicId,question,reason,whatWentWrong:wrong,correctConcept:concept,nextReview:next,lastReview:date,status,reviews:[]});close()}}><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Matéria<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setTopicId('')}}>{store.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="full">Assunto<select value={topicId||topics[0]?.id||''} onChange={e=>setTopicId(e.target.value)}><option value="">Selecione</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="full">Questão<textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Cole ou descreva a questão"/></label><label>Motivo do erro<select value={reason} onChange={e=>setReason(e.target.value as ErrorReason)}>{['Não conhecia o conteúdo','Confundi conceitos','Errei por interpretação','Errei por distração','Errei cálculo','Chutei','Esqueci o conteúdo'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as ErrorStatus)}><option>Pendente</option><option>Revisado</option><option>Dominado</option></select></label><label className="full">O que eu errei?<textarea value={wrong} onChange={e=>setWrong(e.target.value)}/></label><label className="full">Conceito correto<textarea value={concept} onChange={e=>setConcept(e.target.value)}/></label><label>Próxima revisão<input type="date" value={next} onChange={e=>setNext(e.target.value)}/></label><button className="primary-button full">Salvar erro</button></form></Modal>}
