'use client'
import {useMemo,useState} from 'react'
import {BarChart3,CalendarDays,ChevronDown,Target,TrendingUp} from 'lucide-react'
import type {StudyState} from '@/types/study'
import {pct} from '@/types/study'

export function PerformancePage({store}:{store:StudyState}){
 const [period,setPeriod]=useState('Últimos 30 dias')
 const totals=useMemo(()=>store.sessions.reduce((a,s)=>({questions:a.questions+s.quantity,correct:a.correct+s.correct}),{questions:0,correct:0}),[store.sessions])
 const accuracy=pct(totals.correct,totals.questions)
 const bySubject=store.subjects.map(subject=>{const sessions=store.sessions.filter(s=>s.subjectId===subject.id);const questions=sessions.reduce((n,s)=>n+s.quantity,0);const correct=sessions.reduce((n,s)=>n+s.correct,0);return {...subject,questions,accuracy:pct(correct,questions)}}).filter(s=>s.questions)
 return <div className="stack performance-page"><div className="page-actions"><div><h2>Desempenho</h2><p>Entenda sua evolução e encontre os assuntos que mais precisam de atenção.</p></div><label className="period-select"><CalendarDays size={16}/><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Últimos 7 dias</option><option>Últimos 30 dias</option><option>Últimos 90 dias</option></select><ChevronDown size={15}/></label></div><div className="metrics"><div className="metric purple"><div className="metric-dot"/><small>Questões respondidas</small><strong>{totals.questions}</strong></div><div className="metric blue"><div className="metric-dot"/><small>Percentual de acerto</small><strong>{accuracy}%</strong></div><div className="metric green"><div className="metric-dot"/><small>Melhor matéria</small><strong>{bySubject.sort((a,b)=>b.accuracy-a.accuracy)[0]?.name||'—'}</strong></div><div className="metric orange"><div className="metric-dot"/><small>Meta de acerto</small><strong>{store.settings.masteryPercentage}%</strong></div></div><div className="performance-grid"><section className="panel performance-chart"><div className="panel-heading"><div><h2>Evolução de acertos</h2><p>Percentual médio por período</p></div><TrendingUp size={19}/></div><div className="fake-chart" aria-label="Gráfico de evolução"><div className="chart-bars">{[52,61,58,68,73,69,81,78,86,84,91,88].map((height,i)=><div className="chart-bar" style={{height:`${height}%`}} key={i}><span>{height}%</span></div>)}</div><div className="chart-axis"><span>01/08</span><span>08/08</span><span>15/08</span><span>22/08</span><span>Hoje</span></div></div></section><section className="panel performance-goals"><div className="panel-heading"><div><h2>Metas de estudo</h2><p>Seu progresso no período</p></div><Target size={19}/></div><Goal label="Questões" value={totals.questions} target={store.settings.weeklyQuestionsGoal}/><Goal label="Horas estudadas" value={Math.round(totals.questions/10)/10} target={store.settings.weeklyHoursGoal}/><Goal label="Acerto médio" value={accuracy} target={store.settings.masteryPercentage} suffix="%"/></section></div><section className="panel subject-performance"><div className="panel-heading"><div><h2>Desempenho por matéria</h2><p>Compare seus resultados e priorize sua revisão.</p></div><BarChart3 size={19}/></div><div className="performance-table">{bySubject.sort((a,b)=>b.accuracy-a.accuracy).map(s=><div className="performance-row" key={s.id}><span className="performance-subject"><b>{s.name}</b><small>{s.questions} questões</small></span><div className="progress"><i style={{width:`${s.accuracy}%`}}/></div><strong>{s.accuracy}%</strong></div>)}</div></section></div>
}
function Goal({label,value,target,suffix='' }:{label:string;value:number;target:number;suffix?:string}){const progress=Math.min(100,Math.round(value/Math.max(1,target)*100));return <div className="goal"><div><span>{label}</span><b>{value}{suffix} <small>/ {target}{suffix}</small></b></div><div className="progress"><i style={{width:`${progress}%`}}/></div></div>}
