'use client'
import { useState } from 'react'
import { Modal } from '@/components/layout/modal'
import { pct,subjectPerformance,topicPerformance } from '@/types/study'
import type {ErrorEntry,ErrorReason,ErrorStatus,StudyState} from '@/types/study'
import { BookOpen,CircleHelp,ChevronRight,Filter,Plus,Pencil,Trash2,NotebookPen,TriangleAlert } from 'lucide-react'
import { Metric } from '@/components/dashboard/cards'

export function Content({store,selected,select,open,ask}:{store:any;selected:string;select:any;open:any;ask:any}){const topics=store.topics.filter((t:any)=>t.subjectId===selected);return <div className="stack"><div className="page-actions"><div><h2>Gerencie seu conteúdo</h2><p>Organize matérias e acompanhe a evolução real por assunto.</p></div><button className="primary-button" onClick={()=>open('subject')}><Plus size={17}/>Nova matéria</button></div><div className="content-grid"><div className="panel subjects-list"><div className="panel-heading"><h2>Matérias</h2><span className="count">{store.subjects.length}</span></div><div className="scroll-list">{store.subjects.map((s:any)=><div className="subject-entry" key={s.id}><button className={s.id===selected?'subject-row selected':'subject-row'} onClick={()=>select(s.id)}><span><b>{s.name}</b><small>{store.topics.filter((t:any)=>t.subjectId===s.id).length} {store.topics.filter((t:any)=>t.subjectId===s.id).length===1?'assunto':'assuntos'}</small></span></button><div className="subject-actions"><button aria-label={`Editar ${s.name}`} onClick={()=>open('subject',s)}><Pencil size={13}/></button><button aria-label={`Excluir ${s.name}`} onClick={()=>ask({name:s.name,action:()=>store.deleteSubject(s.id)})}><Trash2 size={13}/></button></div></div>)}</div></div><div className="panel topic-panel"><div className="panel-heading"><div><h2>{store.subjects.find((s:any)=>s.id===selected)?.name||'Selecione uma matéria'}</h2><p>Progresso por questões registradas</p></div>{selected&&<button className="secondary-button" onClick={()=>open('topic')}><Plus size={16}/>Adicionar assunto</button>}</div><div className="scroll-list">{topics.map((t:any)=>{const x=topicPerformance(t.id,store.sessions);return <div className="topic-card" key={t.id}><div className="topic-main"><div><h3>{t.name}</h3><p>{x.q} questões · {x.c} acertos · {x.e} erros</p></div><b className="topic-pct">{x.percentage}%</b></div><div className="progress"><i style={{width:`${x.percentage}%`}}/></div><div className="topic-actions"><button onClick={()=>open('topic',t)}><Pencil size={14}/>Editar</button><button onClick={()=>ask({name:t.name,action:()=>store.deleteTopic(t.id)})}><Trash2 size={14}/>Excluir</button></div></div>})}</div></div></div></div>}
