'use client'
import { useState } from 'react'
import { Modal } from '@/components/layout/modal'
import { pct,subjectPerformance,topicPerformance } from '@/types/study'
import type {ErrorEntry,ErrorReason,ErrorStatus,StudyState} from '@/types/study'
import { BookOpen,CircleHelp,ChevronRight,Filter,Plus,Pencil,Trash2,NotebookPen,TriangleAlert } from 'lucide-react'
import { Metric } from '@/components/dashboard/cards'

export function SessionModal({store,item,close}:{store:any;item:any;close:any}){const contextSubjectId=item?.contextSubjectId;const onSaved=item?.onSaved;const session=item;const [subjectId,setSubject]=useState(session?.subjectId||contextSubjectId||store.subjects[0]?.id||''),[topicId,setTopic]=useState(session?.topicId||''),[date,setDate]=useState(session?.date||new Date().toISOString().slice(0,10)),[quantity,setQuantity]=useState(session?.quantity||20),[correct,setCorrect]=useState(session?.correct||15);const topics=store.topics.filter((t:any)=>t.subjectId===subjectId);return <Modal title={session?'Editar sessão':'Registrar questões'} close={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();const data={date,subjectId,topicId:topicId||topics[0]?.id,quantity:Number(quantity),correct:Number(correct),observation:''};if(date&&data.topicId&&data.quantity>0&&data.correct>=0&&data.correct<=data.quantity){session?.id?store.updateSession(session.id,data):store.addSession(data);close()}}}><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{!contextSubjectId&&<label>Matéria<select value={subjectId} onChange={e=>{setSubject(e.target.value);setTopic('')}}>{store.subjects.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label className="full">Assunto<select value={topicId||topics[0]?.id||''} onChange={e=>setTopic(e.target.value)}>{topics.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Questões<input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Acertos<input type="number" min="0" value={correct} onChange={e=>setCorrect(Number(e.target.value))}/></label><button className="primary-button full">Salvar sessão</button></form></Modal>}
